- ecl/network/v2/_proxy.py
- ecl/network/v2/gcp.py
- ecl/network/v2/gw_interface.py
- ecl/network/v2/static_route.py
- ecl/profile.py
- ecl/provider_connectivity/provider_connectivity_service.py
- ecl/provider_connectivity/v2/_proxy.py
- ecl/provider_connectivity/v2/address_assignment.py
- ecl/provider_connectivity/v2/aws_connection.py
- ecl/provider_connectivity/v2/base.py
- ecl/provider_connectivity/v2/exchange_point.py
- ecl/provider_connectivity/v2/gcp_connection.py
- ecl/provider_connectivity/v2/operation.py
- ecl/provider_connectivity/v2/tenant_connection.py
- ecl/provider_connectivity/v2/tenant_connection_request.py
GCP接続用のpropをNetwork APIに追加し、Provider Connectivity APIのv2に対応しました。
> Htysh/if 332/add aws v2

- ecl/block_store/v2/_proxy.py
- ecl/block_store/v2/metadata.py
- requirements.txt
1. volume_id will be automatically added in the metadata list by these two methods
2. create_metadata works as update_metadata by old code
> fix block_store's metadata methods

- ecl/virtual_network_appliance/v1/_proxy.py
- ecl/virtual_network_appliance/v1/virtual_network_appliance.py
I added tags property in virtual network appliance. This change has backward compatibility.
> Add tags property in virtual network appliance

- setup.cfg
> ➕ version up

- ecl/dns/v2/name_server.py
- ecl/dns/v2/recordset.py
- ecl/dns/v2/zone.py
> fix dns endpoint by add version number

- ecl/compute/v2/_proxy.py
If an image name is specified in find_image, it is converted to an image ID.
> :bug: IF-3897 modify the find image method

- ecl/baremetal/v2/_proxy.py
- ecl/baremetal/v2/server.py
added type param to baremetal server stop command.
type param is SOFT and HARD.
If type param is not specified, it is SOFT.
> added type param to baremetal server stop command

- ecl/network/v2/_proxy.py
- ecl/network/v2/fic.py
- ecl/network/v2/qos_option.py
- ecl/network/v2/quota.py
- ecl/network/v2/static_route.py
Added API of FIC connection to SDK.
> Added FIC API

- .github/CODEOWNERS
Add CODEOWNERS required for default reviewer settings.
> :books: IF-4195 add CODEOWNERS

- .github/CODEOWNERS
> :fire: IF-4195 Delete CODEOWNERS

- ecl/baremetal/v2/_proxy.py
- ecl/baremetal/v2/server.py
I made the following changes in bare metal server action
* Remove boot_mode parameter from start_server and reboot_server
* Rename type parameter to shutdown_type due to shadowing
* Add change_boot_mode
> Add bare metal boot mode change

- ecl/baremetal/v2/server.py
Add boot mode request body "boot_mode"
> ysssasaki_IF-4811_fix_boot_mode_request

- ecl/provider_connectivity/v2/operation.py
Add `error` field to `Operation` in Provider Connectivity
> M miwa if 5299 tc add detailed error

- ecl/mvna/mvna_service.py
- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/base.py
- ecl/mvna/v1/load_balancer.py
- ecl/profile.py
Add Managed Load Balancer Resource.
> Add managed load balancer

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/target_group.py
Add MVNA Target Group Resource.
> Add MVNA target group resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/certificate.py
> Add MVNA certificate resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/listener.py
> Add MVNA listener resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/maintenance.py
> Add MVNA maintenance resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/plan.py
> Add MVNA plan resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/health_monitor.py
Add MVNA Health Monitor Resource.
> Add MVNA health monitor resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/policy.py
> Add MVNA policy resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/route.py
> Add MVNA route resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/rule.py
> Add MVNA rule resource

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/base.py
- ecl/mvna/v1/certificate.py
- ecl/mvna/v1/health_monitor.py
- ecl/mvna/v1/listener.py
- ecl/mvna/v1/load_balancer.py
- ecl/mvna/v1/maintenance.py
- ecl/mvna/v1/plan.py
- ecl/mvna/v1/policy.py
- ecl/mvna/v1/route.py
- ecl/mvna/v1/rule.py
- ecl/mvna/v1/target_group.py
- List 処理において Query Parameter をサポート
- Show 系の処理において `changes` Query Parameter をサポート
- Action, Delete Load Balancer において `X-MVNA-Request-Id` をサポート
> Support additional mvna parameter

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/tls_security_policy.py
> Add MVNA TLS Security Policy

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/base.py
- ecl/mvna/v1/health_monitor.py
- ecl/mvna/v1/load_balancer.py
- ecl/mvna/v1/target_group.py
> Follow MVNA api spec changes

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/health_monitor.py
- ecl/mvna/v1/load_balancer.py
- ecl/mvna/v1/plan.py
- ecl/mvna/v1/policy.py
> NaoShark IF-5874 drop mvna day2 functions

- ecl/mvna/v1/_proxy.py
This PR enables update mvNA relevant objects with following parameters.
- "" (blank string)
- {} (blank object)
> Enable Update with blank parameter

- ecl/mvna/v1/_proxy.py
health monitorのportをicmpにした場合，port=0となり配列に格納されない問題を修正
> IF-6142 fix  operator of health monitor

- ecl/baremetal/v2/_proxy.py
- ecl/baremetal/v2/chassis.py
- ecl/baremetal/v2/server.py
- ecl/tests/functional/baremetal/test_chassis.py
- ecl/tests/functional/baremetal/test_server.py
- ecl/tests/unit/baremetal/v2/test_charssis.py
- Add an interface for BTO to the baremetal server API
> :sparkles: add bto baremetals api

- ecl/network/v2/_proxy.py
- ecl/network/v2/security_group_rule.py
- ecl/tests/unit/network/v2/test_security_group_rule.py
- List Security Group Rule
- Create Security Group Rule
- Show Security Group Rule
- Delete  Security Group Rule
> :sparkles: IF-7067 add security group rules api

- ecl/network/v2/_proxy.py
- ecl/network/v2/port.py
- ecl/network/v2/quota.py
- ecl/tests/unit/network/v2/test_port.py
- ecl/tests/unit/network/v2/test_quota.py
> Revert ":bug: IF-7068 fix existing api"

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/policy.py
- ecl/mvna/v1/tls_policy.py
Description of the Change
- create_policyのコメントアウトを削除
- create_staged_policy_configurationのコメントアウト削除
- update_staged_policy_configurationのコメントアウト削除
- tls_security_policyをtls_policyに変更
- rule系のコメントアウトを削除
- tls_policy系のコメントアウトを削除
- ecl/mvna/v1/tls_policy.py
- tls_security_policy.pyをtls_policy.pyに変更
- TLSSecurityPolicyをTLSPolicyに変更
- ecl/mvna/v1/policy.py
- `sorry_page_url` `certificate_id` `tls_security_policy_id`のコメントアウト削除
- tls_security_policyをtls_policyに変更
> :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105)

- ecl/mvna/v1/_proxy.py
Description of the Change
- certificate系のコメントアウトを削除
- create_certificateの「name」「description」「tags」のif に「is not None」を追加
- update_certificateの「name」「description」「tags」のif に「is not None」を追加
> :sparkles: IF-7410 Append mLB SSL Certificates API of mVNA Day2 (#106)

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/health_monitor.py
Description of the Change
- create_health_monitorのコメントアウトを削除
- create_staged_health_monitor_configurationのコメントアウト削除
- update_staged_health_monitor_configurationのコメントアウト削除
- ecl/mvna/v1/health_monitor.py
- コメントアウト削除
画面設計書、API仕様書と比較して特にパラメータ名の変更点等がないように見受けられたため
Day2予定としてコメントアウトされていたもののコメントアウト削除のみ
> :sparkles: IF-7419 Append mLB HealthMonitor API of mVNA Day2 (#107)

- ecl/storage/v1/storage.py
- ecl/storage/v1/volume.py
- ecl/tests/unit/storage/v1/test_storage.py
- ecl/tests/unit/storage/v1/test_volume.py
* :sparkles: IF-7320 add smb_propaerties to storage
* :sparkles: IF-7320 add smb_propaerties to storage
Co-authored-by: Yoshiki Kashiwabara <yoshikikashiwabara@A1000585-dcp0403kashiwabaray01.local>
> :sparkles: IF-7320 add smb_propaerties to storage (#120)

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/base.py
- ecl/mvna/v1/health_monitor.py
- ecl/mvna/v1/load_balancer.py
- ecl/mvna/v1/plan.py
- ecl/mvna/v1/policy.py
- ecl/mvna/v1/system_update.py
- ecl/mvna/v1/tls_policy.py
* :sparkles: IF-7416 Append mLB Body API of mVNA Day2 (#104)
* :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105) (#105)
* :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105)
* :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105) add 'is not None'
* :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105) add all 'is not None'
* :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105) add all 'is not None'
* :sparkles: IF-7412 Append mLB Rules API of mVNA Day2 (#105) modify 'TLS Security Policy'
Co-authored-by: ikegami.shota <shota.ikegami@ntt.com>
* :sparkles: IF-7410 Append mLB SSL Certificates API of mVNA Day2 (#106) (#106)
* :sparkles: IF-7410 Append mLB SSL Certificates API of mVNA Day2 (#106)
* :sparkles: IF-7410 Append mLB SSL Certificates API of mVNA …
> Add mvna get staged method (#127)

- setup.cfg
> :bookmark: IF-9049 version up

- ecl/sss/sss_service.py
- ecl/sss/v2/_proxy.py
- ecl/sss/v2/token.py
- ecl/tests/functional/sss/v2/test_token.py
- ecl/tests/unit/sss/test_sss_service.py
- ecl/tests/unit/sss/v2/test_token.py
Add SSS API (for Admin Endpoint)
- POST /tokens/users/{ecid}
> :sparkles: add sss get user token api

- ecl/sss/sss_service.py
- ecl/sss/v2/_proxy.py
- ecl/sss/v2/token.py
- ecl/tests/functional/sss/v2/test_token.py
- ecl/tests/unit/sss/test_sss_service.py
- ecl/tests/unit/sss/v2/test_token.py
- https://github.com/nttcom/eclsdk/pull/130
> :sparkles: add sss get user token api (#130)

- ecl/network/v2/_proxy.py
- ecl/network/v2/mec.py
- ecl/network/v2/qos_option.py
- ecl/network/v2/quota.py
- ecl/network/v2/static_route.py
- ecl/tests/unit/network/v2/test_mec_gateway.py
- ecl/tests/unit/network/v2/test_mec_interface.py
- ecl/tests/unit/network/v2/test_mec_service.py
- ecl/tests/unit/network/v2/test_quota.py
> :sparkles: Add MEC-GW API IF-10332 (#134)

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/policy.py
Add idle_timeout to policy parameters
- Add idle_timeout as a parameter during policy creation, creation and update config status.
- ecl/mvna/v1/policy.py
- Add idle_timeout to policy parameters.
> IF-10369 add parameter idle timeout

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/policy.py
- https://github.com/nttcom/eclsdk/pull/137
> IF-10369 add parameter idle timeout (#137)

- ecl/baremetal/v2/_proxy.py
- ecl/baremetal/v2/server.py
- ecl/dedicated_hypervisor/v1/_proxy.py
- ecl/dedicated_hypervisor/v1/server.py
- https://github.com/nttcom/eclsdk/pull/139
> :sparkles: Modification Beremetal Dedicated Hypervisor API IF-10576

- ecl/virtual_network_appliance/v1/_proxy.py
* Add initial config to vSRX
- ecl/virtual_network_appliance/v1/_proxy.py
- Add initial_config parameter to create_virtual_network_appliance
> IF-11939 Add initial config to vSRX

- ecl/virtual_network_appliance/v1/_proxy.py
> IF-11939 Add initial config to vSRX (#147)

- ecl/image/v2/image.py
- ecl/session.py
- ecl/tests/unit/test_session.py
* Set Value In Accept  Header Of SDK Request
- ecl/session.py
- Add Value In Accept  Header
- ecl/tests/unit/test_session.py
- Add Value In Accept  Header Of SDK Request unittest
- ecl/image/v2/image.py
- Add Value In Accept  Header(application/octet-stream)
> IF-5955 Set Value In Accept  Header Of SDK Request

- ecl/network/v2/load_balancer_plan.py
- ecl/tests/functional/network/v2/test_load_balancer_plan.py
* Add update_enabled for load balancer plan
- ecl/network/v2/load_balancer_plan.py
- Add class variable update_enabled
- ecl/tests/functional/network/v2/test_load_balancer_plan.py
- Add check of enabled, update_enabled
> :sparkles: Add update_enabled for load balancer plan IF-13986

- ecl/mvna/v1/_proxy.py
- ecl/mvna/v1/plan.py
- ecl/mvna/v1/policy.py
- ecl/mvna/v1/rule.py
Description of the Change
- upload_certificate
- Add passphrase
- create_policy
- Add persistence_timeout
- Add server_name_indications
- Add backup_target_group_id
- create_staged_policy_configuration
- Add persistence_timeout
- Add server_name_indications
- Add backup_target_group_id
- update_staged_policy_configuration
- Add persistence_timeout
- Add server_name_indications
- Add backup_target_group_id
- create_rule
- Add backup_target_group_id
- create_staged_rule_configuration
- Add backup_target_group_id
- update_staged_rule_configuration
- Add backup_target_group_id
- ecl/mvna/v1/plan.py
- Add max_number_of_server_name_indications
- ecl/mvna/v1/policy.py
- Add persistence_timeout
- Add server_name_indications
- Add backup_target_group_id
- …
> :sparkles: Support mVNA Day4 IF-13381

- ecl/dedicated_hypervisor/exceptions.py
- ecl/dedicated_hypervisor/v1/_proxy.py
- ecl/dedicated_hypervisor/v1/server.py
- ecl/dedicated_hypervisor/v1/vcenter.py
* Add vCenter API
- * ecl/dedicated_hypervisor/v1/_proxy.py
- Add method below
- show_vcenter
- register_vcenter
- update_vcenter
- delete_vcenter
- * ecl/dedicated_hypervisor/exceptions.py
- Add vCenter massage case
- * ecl/dedicated_hypervisor/v1/vcenter.py
- Add newly created file 
* PR was recreated because prior PR was closed for fixing branch name
* old PR: https://github.com/nttcom/eclsdk/pull/160
> Kashiwabara if 14188 v center addition

- ecl/dedicated_hypervisor/v1/server.py
* Add image_name
*  ecl/dedicated_hypervisor/v1/server.py
> :sparkles: Changed the method  of obtaining Image-names in BMDH IF-14514

- ecl/dedicated_hypervisor/exceptions.py
- ecl/dedicated_hypervisor/v1/_proxy.py
- ecl/dedicated_hypervisor/v1/vcenter.py
- ecl/dedicated_hypervisor/v1/vsphere_contract.py
* Modifying to allow multiple servers to register
- ecl/dedicated_hypervisor/v1/_proxy.py
- Add parameter link_local_address to register_vcenter and update_vcenter.
- Add new method available_addresses_vcenter
- ecl/dedicated_hypervisor/v1/vcenter.py
- Add parameter link_local_address to register and update.
- Add LinkLocalAddresses class.
* PR was recreated because prior PR was closed for fixing branch name
* old PR: https://github.com/nttcom/eclsdk/pull/170
> Kashiwabara y if 14948 v center allow multiple servers new

- ecl/dedicated_hypervisor/v1/vsphere_contract.py
* Fix how to judge contract_renewal is specified
- ecl/dedicated_hypervisor/v1/vsphere_contract.py
> :bug: Fix how to judge contract_renewal is specified IF-15238

- setup.cfg
- Update to new corporate name 
- setup.cfg
-  Change corporate name from NTT Communications to NTT DOCOMO BUSINESS
> :sparkles: Update corporate name IF-15454

- ecl/block_store/v2/volume.py
* Change the key name in retype (change from dryRun to dry_run)
* ecl/block_store/v2/volume.py
- Change the key name in retype (change from dryRun to dry_run)
> :bug: Fix added japanese translation for volume list status IF-15753
